### ISSUE TITLE
Error: expected security_rule.0.protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP │ 

### ISSUE THREAD

**Issue by rtrentin73** [AviatrixSystems/terraform-aviatrix-azure-controller#21]
Error: expected security_rule.0.protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP
│ 
│   with module.aviatrix_controller_azure.module.aviatrix_controller_build.azurerm_network_security_group.aviatrix_controller_nsg,
│   on .terraform/modules/aviatrix_controller_azure/modules/aviatrix_controller_build/main.tf line 51, in resource "azurerm_network_security_group" "aviatrix_controller_nsg":
│   51: resource "azurerm_network_security_group" "aviatrix_controller_nsg" {
│

**Comment by shuoliugit** [comment]
fixed
